server:
  port: 8090
  servlet:
    context-path: /ac
meta:
  security:
    oauth2:
      storeType: jwt
      client: jdbc
      jwtSigningKey: meta
  authcenter:
    account:
      pwderr:
        cnt_limit_verifycode: 3
spring:
  application:
    name: meta-authentication-center-api
  datasource:
    url: jdbc:mysql://8.142.222.226:3306/meta_auth_center?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: ems@123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 14
    port: 6379
    host: 8.142.222.226
    password: ems@123
    lettuce:
      pool:
        max-active: 8
  session:
    store-type: redis



jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 8.142.222.226
      port: 6379
      password: ems@123
      database: 1
logging:
  level:
    org.springframework.security: debug
